name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  s2n-bignum-arm-tests:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependent packages
      run: |
        sudo apt update
        sudo apt install valgrind

    - name: Run tests
      run: |
        cd arm
        make
        cd ../tests
        CC=gcc make complete
        CC=clang make complete
        make ctCheck
        cd ../benchmarks
        CC=gcc make
        CC=clang make
				# AWS-LC test
        cd ..
        git clone https://github.com/aws/aws-lc.git --depth=1
        cd aws-lc/third_party/s2n-bignum
        rm -rf ./s2n-bignum-imported
        GITHUB_REPOSITORY=$GITHUB_REPOSITORY GITHUB_TARGET=$GITHUB_HEAD_REF ./import.sh
        cd ../..
        mkdir aws-lc-build && cd aws-lc-build
        cmake3 -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFIPS=On ../aws-lc
        ninja-build run_tests
        cmake3 -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFIPS=Off ../aws-lc
        ninja-build run_tests

  s2n-bignum-x86-tests:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        cd x86
        make
        cd ../x86_att && make clobber && make && git diff --exit-code .
        cd ../tests
        CC=gcc make complete
        CC=clang make complete
        make ctCheck
        cd ../benchmarks
        CC=gcc make
        CC=clang make
				# AWS-LC test
        cd ..
        git clone https://github.com/aws/aws-lc.git --depth=1
        cd aws-lc/third_party/s2n-bignum
        rm -rf ./s2n-bignum-imported
        GITHUB_REPOSITORY=$GITHUB_REPOSITORY GITHUB_TARGET=$GITHUB_HEAD_REF ./import.sh
        cd ../..
        mkdir aws-lc-build && cd aws-lc-build
        cmake3 -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFIPS=On ../aws-lc
        ninja-build run_tests
        cmake3 -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFIPS=Off ../aws-lc
        ninja-build run_tests
